# Generated by Django 5.0.2 on 2024-02-29 17:31

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_alter_portfolio_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioimage',
            name='description',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to='weblog.blog')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='weblog_blog_created_bc9da8_idx')],
            },
        ),
    ]
